var searchData=
[
  ['características_0',['Características',['../index.html#autotoc_md4',1,'']]],
  ['características_20adicionales_1',['Características Adicionales',['../index.html#autotoc_md9',1,'']]],
  ['características_20principales_3a_2',['Características principales:',['../index.html#autotoc_md51',1,'']]],
  ['casos_20de_20uso_3a_3',['Casos de uso:',['../index.html#autotoc_md31',1,'']]],
  ['categorías_4',['categorías',['../index.html#autotoc_md45',1,'Categorías'],['../index.html#autotoc_md7',1,'Gestión de Categorías']]],
  ['categoria_5',['Categoria',['../classdev_1_1luisvives_1_1trabajoprogramacionsegundo_1_1productos_1_1model_1_1Categoria.html',1,'dev::luisvives::trabajoprogramacionsegundo::productos::model']]],
  ['categoria_2ejava_6',['Categoria.java',['../Categoria_8java.html',1,'']]],
  ['categoriesmapper_7',['CategoriesMapper',['../classdev_1_1luisvives_1_1trabajoprogramacionsegundo_1_1productos_1_1mapper_1_1CategoriesMapper.html',1,'dev::luisvives::trabajoprogramacionsegundo::productos::mapper']]],
  ['categoriesmapper_2ejava_8',['CategoriesMapper.java',['../CategoriesMapper_8java.html',1,'']]],
  ['categoriesmappertest_2ejava_9',['CategoriesMapperTest.java',['../CategoriesMapperTest_8java.html',1,'']]],
  ['categoriesrepository_10',['CategoriesRepository',['../interfacedev_1_1luisvives_1_1trabajoprogramacionsegundo_1_1productos_1_1repository_1_1CategoriesRepository.html',1,'dev::luisvives::trabajoprogramacionsegundo::productos::repository']]],
  ['categoriesrepository_2ejava_11',['CategoriesRepository.java',['../CategoriesRepository_8java.html',1,'']]],
  ['categoriesrepositorytest_2ejava_12',['CategoriesRepositoryTest.java',['../CategoriesRepositoryTest_8java.html',1,'']]],
  ['categoriesrestcontroller_13',['categoriesrestcontroller',['../classdev_1_1luisvives_1_1trabajoprogramacionsegundo_1_1productos_1_1controller_1_1CategoriesRestController.html',1,'dev.luisvives.trabajoprogramacionsegundo.productos.controller.CategoriesRestController'],['../classdev_1_1luisvives_1_1trabajoprogramacionsegundo_1_1productos_1_1controller_1_1CategoriesRestController.html#a4a81ee9d350f8ef7cad789564756d43b',1,'dev.luisvives.trabajoprogramacionsegundo.productos.controller.CategoriesRestController.CategoriesRestController()']]],
  ['categoriesrestcontroller_2ejava_14',['CategoriesRestController.java',['../CategoriesRestController_8java.html',1,'']]],
  ['categoriesrestcontrollertest_2ejava_15',['CategoriesRestControllerTest.java',['../CategoriesRestControllerTest_8java.html',1,'']]],
  ['categoriesservice_16',['CategoriesService',['../interfacedev_1_1luisvives_1_1trabajoprogramacionsegundo_1_1productos_1_1service_1_1CategoriesService.html',1,'dev::luisvives::trabajoprogramacionsegundo::productos::service']]],
  ['categoriesservice_2ejava_17',['CategoriesService.java',['../CategoriesService_8java.html',1,'']]],
  ['categoriesserviceimpl_18',['categoriesserviceimpl',['../classdev_1_1luisvives_1_1trabajoprogramacionsegundo_1_1productos_1_1service_1_1CategoriesServiceImpl.html#add81d69c3243f4270ab64ded7c191699',1,'dev.luisvives.trabajoprogramacionsegundo.productos.service.CategoriesServiceImpl.CategoriesServiceImpl()'],['../classdev_1_1luisvives_1_1trabajoprogramacionsegundo_1_1productos_1_1service_1_1CategoriesServiceImpl.html',1,'dev.luisvives.trabajoprogramacionsegundo.productos.service.CategoriesServiceImpl']]],
  ['categoriesserviceimpl_2ejava_19',['CategoriesServiceImpl.java',['../CategoriesServiceImpl_8java.html',1,'']]],
  ['categoriesserviceimpltest_2ejava_20',['CategoriesServiceImplTest.java',['../CategoriesServiceImplTest_8java.html',1,'']]],
  ['categoryexception_21',['categoryexception',['../classdev_1_1luisvives_1_1trabajoprogramacionsegundo_1_1productos_1_1exceptions_1_1CategoryException.html',1,'dev.luisvives.trabajoprogramacionsegundo.productos.exceptions.CategoryException'],['../classdev_1_1luisvives_1_1trabajoprogramacionsegundo_1_1productos_1_1exceptions_1_1CategoryException.html#a9a40305b0779a3d31fee1a9b26e9a740',1,'dev.luisvives.trabajoprogramacionsegundo.productos.exceptions.CategoryException.CategoryException()']]],
  ['categoryexception_2ejava_22',['CategoryException.java',['../CategoryException_8java.html',1,'']]],
  ['categorynotfoundexception_23',['categorynotfoundexception',['../classdev_1_1luisvives_1_1trabajoprogramacionsegundo_1_1productos_1_1exceptions_1_1CategoryNotFoundException.html',1,'dev.luisvives.trabajoprogramacionsegundo.productos.exceptions.CategoryNotFoundException'],['../classdev_1_1luisvives_1_1trabajoprogramacionsegundo_1_1productos_1_1exceptions_1_1CategoryNotFoundException.html#ad98d94ce8a6b370a6e1f400fa4a07a91',1,'dev.luisvives.trabajoprogramacionsegundo.productos.exceptions.CategoryNotFoundException.CategoryNotFoundException(String name)'],['../classdev_1_1luisvives_1_1trabajoprogramacionsegundo_1_1productos_1_1exceptions_1_1CategoryNotFoundException.html#ad52f99212628418ec59cc62f2b08da02',1,'dev.luisvives.trabajoprogramacionsegundo.productos.exceptions.CategoryNotFoundException.CategoryNotFoundException(Long id)']]],
  ['categorynotfoundexception_2ejava_24',['CategoryNotFoundException.java',['../CategoryNotFoundException_8java.html',1,'']]],
  ['categoryvalidationexception_25',['categoryvalidationexception',['../classdev_1_1luisvives_1_1trabajoprogramacionsegundo_1_1productos_1_1exceptions_1_1CategoryValidationException.html#a9b8d99f63525d519cc8a7f0798d897e8',1,'dev.luisvives.trabajoprogramacionsegundo.productos.exceptions.CategoryValidationException.CategoryValidationException()'],['../classdev_1_1luisvives_1_1trabajoprogramacionsegundo_1_1productos_1_1exceptions_1_1CategoryValidationException.html',1,'dev.luisvives.trabajoprogramacionsegundo.productos.exceptions.CategoryValidationException']]],
  ['categoryvalidationexception_2ejava_26',['CategoryValidationException.java',['../CategoryValidationException_8java.html',1,'']]],
  ['cliente_27',['Cliente',['../namespacedev_1_1luisvives_1_1trabajoprogramacionsegundo_1_1pedidos_1_1model.html#ad569ab3b621a4fdac9aaccd1d56e539e',1,'dev::luisvives::trabajoprogramacionsegundo::pedidos::model']]],
  ['cliente_2ejava_28',['Cliente.java',['../Cliente_8java.html',1,'']]],
  ['clientenotificaciondto_29',['ClienteNotificacionDto',['../classdev_1_1luisvives_1_1trabajoprogramacionsegundo_1_1notificaciones_1_1dto_1_1pedidos_1_1ClienteNotificacionDto.html',1,'dev::luisvives::trabajoprogramacionsegundo::notificaciones::dto::pedidos']]],
  ['clientenotificaciondto_2ejava_30',['ClienteNotificacionDto.java',['../ClienteNotificacionDto_8java.html',1,'']]],
  ['clonar_20el_20repositorio_31',['Clonar el repositorio',['../index.html#autotoc_md17',1,'']]],
  ['cobertura_32',['Generar reporte de cobertura',['../index.html#autotoc_md20',1,'']]],
  ['cobertura_20jacoco_33',['Reportes de Cobertura (JaCoCo)',['../index.html#autotoc_md33',1,'']]],
  ['com_20adrianhersac_20github_20com_20adrianhersac_20a_34',['- &lt;strong&gt;GitHub&lt;/strong&gt;: &lt;a href=&quot;https://github.com/AdrianHerSac&quot; &gt;github.com/AdrianHerSac&lt;/a&gt;',['../md__2home_2runner_2work_2TrabajoProgramacionSegundo_2TrabajoProgramacionSegundo_2LICENSE.html#autotoc_md76',1,'']]],
  ['compilar_20el_20proyecto_35',['Compilar el proyecto',['../index.html#autotoc_md18',1,'']]],
  ['completa_3a_36',['Documentación completa:',['../index.html#autotoc_md38',1,'']]],
  ['con_20docker_37',['Despliegue con Docker',['../index.html#autotoc_md23',1,'']]],
  ['condiciones_3a_38',['Condiciones:',['../md__2home_2runner_2work_2TrabajoProgramacionSegundo_2TrabajoProgramacionSegundo_2LICENSE.html#autotoc_md70',1,'']]],
  ['configuración_39',['Instalación y Configuración',['../index.html#autotoc_md16',1,'']]],
  ['construcción_20manual_40',['Construcción manual',['../index.html#autotoc_md25',1,'']]],
  ['contacto_41',['Contacto',['../md__2home_2runner_2work_2TrabajoProgramacionSegundo_2TrabajoProgramacionSegundo_2LICENSE.html#autotoc_md75',1,'']]],
  ['contenido_20del_20dashboard_3a_42',['Contenido del Dashboard:',['../index.html#autotoc_md34',1,'']]],
  ['contenidos_43',['📋 Tabla de Contenidos',['../index.html#autotoc_md2',1,'']]],
  ['contribuciones_44',['Contribuciones',['../md__2home_2runner_2work_2TrabajoProgramacionSegundo_2TrabajoProgramacionSegundo_2LICENSE.html#autotoc_md73',1,'']]],
  ['create_45',['CREATE',['../enumdev_1_1luisvives_1_1trabajoprogramacionsegundo_1_1notificaciones_1_1models_1_1Tipo.html#a56db7741afb45b22cc847bd9b7125ed0',1,'dev::luisvives::trabajoprogramacionsegundo::notificaciones::models::Tipo']]]
];
