var searchData=
[
  ['página_20de_20test_0',['Página de Test',['../index.html#autotoc_md29',1,'']]],
  ['página_20de_20test_20interactiva_1',['Página de Test Interactiva',['../index.html#autotoc_md50',1,'']]],
  ['pageresponsedto_2',['PageResponseDTO',['../classdev_1_1luisvives_1_1trabajoprogramacionsegundo_1_1common_1_1dto_1_1PageResponseDTO.html',1,'dev::luisvives::trabajoprogramacionsegundo::common::dto']]],
  ['pageresponsedto_2ejava_3',['PageResponseDTO.java',['../PageResponseDTO_8java.html',1,'']]],
  ['pagetodto_4',['pagetodto',['../classdev_1_1luisvives_1_1trabajoprogramacionsegundo_1_1usuarios_1_1mapper_1_1UsuariosMapper.html#a5f7609497ca8a25ba01f5982ad2656ed',1,'dev.luisvives.trabajoprogramacionsegundo.usuarios.mapper.UsuariosMapper.pageToDTO()'],['../classdev_1_1luisvives_1_1trabajoprogramacionsegundo_1_1productos_1_1mapper_1_1ProductoMapper.html#ae64352cff9629e0bb3a51636536cf719',1,'dev.luisvives.trabajoprogramacionsegundo.productos.mapper.ProductoMapper.pageToDTO()']]],
  ['paso_20a_20paso_3a_5',['Proceso paso a paso:',['../index.html#autotoc_md55',1,'']]],
  ['paso_3a_6',['Proceso paso a paso:',['../index.html#autotoc_md55',1,'']]],
  ['passwordencoder_7',['passwordEncoder',['../classdev_1_1luisvives_1_1trabajoprogramacionsegundo_1_1common_1_1Security_1_1SecurityConfig.html#aed11f48d38c476d13a869eee5cc30678',1,'dev::luisvives::trabajoprogramacionsegundo::common::Security::SecurityConfig']]],
  ['patch_8',['patch',['../interfacedev_1_1luisvives_1_1trabajoprogramacionsegundo_1_1productos_1_1service_1_1Service.html#aca1e112c381ecafe129999b52fedd1f4',1,'dev.luisvives.trabajoprogramacionsegundo.productos.service.Service.patch()'],['../classdev_1_1luisvives_1_1trabajoprogramacionsegundo_1_1productos_1_1service_1_1ProductoServiceImpl.html#a9ba7eac97c206c71b361750e3a42a3fe',1,'dev.luisvives.trabajoprogramacionsegundo.productos.service.ProductoServiceImpl.patch()'],['../classdev_1_1luisvives_1_1trabajoprogramacionsegundo_1_1productos_1_1service_1_1CategoriesServiceImpl.html#a0f3ea2e7e6c8b606f6c18f4b4a41d783',1,'dev.luisvives.trabajoprogramacionsegundo.productos.service.CategoriesServiceImpl.patch()'],['../interfacedev_1_1luisvives_1_1trabajoprogramacionsegundo_1_1productos_1_1service_1_1CategoriesService.html#aea8372577da4d844bf4b10141da15b68',1,'dev.luisvives.trabajoprogramacionsegundo.productos.service.CategoriesService.patch()'],['../classdev_1_1luisvives_1_1trabajoprogramacionsegundo_1_1productos_1_1controller_1_1ProductoRestController.html#a07deca2ff8b2428ea9c3171f577ccad0',1,'dev.luisvives.trabajoprogramacionsegundo.productos.controller.ProductoRestController.patch()'],['../classdev_1_1luisvives_1_1trabajoprogramacionsegundo_1_1productos_1_1controller_1_1CategoriesRestController.html#a133c0e57f5f4d806b79c8a729cc4b945',1,'dev.luisvives.trabajoprogramacionsegundo.productos.controller.CategoriesRestController.patch()']]],
  ['patchcategoryrequestdto_9',['PATCHcategoryRequestDTO',['../classdev_1_1luisvives_1_1trabajoprogramacionsegundo_1_1productos_1_1dto_1_1category_1_1PATCHcategoryRequestDTO.html',1,'dev::luisvives::trabajoprogramacionsegundo::productos::dto::category']]],
  ['patchcategoryrequestdto_2ejava_10',['PATCHcategoryRequestDTO.java',['../PATCHcategoryRequestDTO_8java.html',1,'']]],
  ['patchproductorequestdto_11',['PATCHProductoRequestDTO',['../classdev_1_1luisvives_1_1trabajoprogramacionsegundo_1_1productos_1_1dto_1_1producto_1_1PATCHProductoRequestDTO.html',1,'dev::luisvives::trabajoprogramacionsegundo::productos::dto::producto']]],
  ['patchproductorequestdto_2ejava_12',['PATCHProductoRequestDTO.java',['../PATCHProductoRequestDTO_8java.html',1,'']]],
  ['pedido_13',['Pedido',['../classdev_1_1luisvives_1_1trabajoprogramacionsegundo_1_1pedidos_1_1model_1_1Pedido.html',1,'dev::luisvives::trabajoprogramacionsegundo::pedidos::model']]],
  ['pedido_2ejava_14',['Pedido.java',['../Pedido_8java.html',1,'']]],
  ['pedidoexception_15',['pedidoexception',['../classdev_1_1luisvives_1_1trabajoprogramacionsegundo_1_1pedidos_1_1exceptions_1_1PedidoException.html#a34d6f1e17bc99e710a4664255e1f5cd0',1,'dev.luisvives.trabajoprogramacionsegundo.pedidos.exceptions.PedidoException.PedidoException()'],['../classdev_1_1luisvives_1_1trabajoprogramacionsegundo_1_1pedidos_1_1exceptions_1_1PedidoException.html',1,'dev.luisvives.trabajoprogramacionsegundo.pedidos.exceptions.PedidoException']]],
  ['pedidoexception_2ejava_16',['PedidoException.java',['../PedidoException_8java.html',1,'']]],
  ['pedidonotificaciondto_17',['PedidoNotificacionDto',['../classdev_1_1luisvives_1_1trabajoprogramacionsegundo_1_1notificaciones_1_1dto_1_1pedidos_1_1PedidoNotificacionDto.html',1,'dev::luisvives::trabajoprogramacionsegundo::notificaciones::dto::pedidos']]],
  ['pedidonotificaciondto_2ejava_18',['PedidoNotificacionDto.java',['../PedidoNotificacionDto_8java.html',1,'']]],
  ['pedidos_19',['pedidos',['../index.html#autotoc_md8',1,'Gestión de Pedidos'],['../index.html#autotoc_md47',1,'Pedidos']]],
  ['pedidosmapper_20',['PedidosMapper',['../classdev_1_1luisvives_1_1trabajoprogramacionsegundo_1_1pedidos_1_1mappers_1_1PedidosMapper.html',1,'dev::luisvives::trabajoprogramacionsegundo::pedidos::mappers']]],
  ['pedidosmapper_2ejava_21',['PedidosMapper.java',['../PedidosMapper_8java.html',1,'']]],
  ['pedidosmappertest_2ejava_22',['PedidosMapperTest.java',['../PedidosMapperTest_8java.html',1,'']]],
  ['pedidosrepository_23',['PedidosRepository',['../interfacedev_1_1luisvives_1_1trabajoprogramacionsegundo_1_1pedidos_1_1repository_1_1PedidosRepository.html',1,'dev::luisvives::trabajoprogramacionsegundo::pedidos::repository']]],
  ['pedidosrepository_2ejava_24',['PedidosRepository.java',['../PedidosRepository_8java.html',1,'']]],
  ['pedidosrepositorytest_2ejava_25',['PedidosRepositoryTest.java',['../PedidosRepositoryTest_8java.html',1,'']]],
  ['pedidosrestcontroller_26',['pedidosrestcontroller',['../classdev_1_1luisvives_1_1trabajoprogramacionsegundo_1_1pedidos_1_1controller_1_1PedidosRestController.html#acf14eeca3b255469c8d88a5d651043b2',1,'dev.luisvives.trabajoprogramacionsegundo.pedidos.controller.PedidosRestController.PedidosRestController()'],['../classdev_1_1luisvives_1_1trabajoprogramacionsegundo_1_1pedidos_1_1controller_1_1PedidosRestController.html',1,'dev.luisvives.trabajoprogramacionsegundo.pedidos.controller.PedidosRestController']]],
  ['pedidosrestcontroller_2ejava_27',['PedidosRestController.java',['../PedidosRestController_8java.html',1,'']]],
  ['pedidosrestcontrollertest_2ejava_28',['PedidosRestControllerTest.java',['../PedidosRestControllerTest_8java.html',1,'']]],
  ['pedidosservice_29',['PedidosService',['../interfacedev_1_1luisvives_1_1trabajoprogramacionsegundo_1_1pedidos_1_1service_1_1PedidosService.html',1,'dev::luisvives::trabajoprogramacionsegundo::pedidos::service']]],
  ['pedidosservice_2ejava_30',['PedidosService.java',['../PedidosService_8java.html',1,'']]],
  ['pedidosserviceimpl_31',['pedidosserviceimpl',['../classdev_1_1luisvives_1_1trabajoprogramacionsegundo_1_1pedidos_1_1service_1_1PedidosServiceImpl.html#a2afd117f0069756d76eb949e0fa28ca0',1,'dev.luisvives.trabajoprogramacionsegundo.pedidos.service.PedidosServiceImpl.PedidosServiceImpl()'],['../classdev_1_1luisvives_1_1trabajoprogramacionsegundo_1_1pedidos_1_1service_1_1PedidosServiceImpl.html',1,'dev.luisvives.trabajoprogramacionsegundo.pedidos.service.PedidosServiceImpl']]],
  ['pedidosserviceimpl_2ejava_32',['PedidosServiceImpl.java',['../PedidosServiceImpl_8java.html',1,'']]],
  ['pedidosserviceimpltest_2ejava_33',['PedidosServiceImplTest.java',['../PedidosServiceImplTest_8java.html',1,'']]],
  ['pedidosvalidator_34',['PedidosValidator',['../classdev_1_1luisvives_1_1trabajoprogramacionsegundo_1_1pedidos_1_1validator_1_1PedidosValidator.html',1,'dev::luisvives::trabajoprogramacionsegundo::pedidos::validator']]],
  ['pedidosvalidator_2ejava_35',['PedidosValidator.java',['../PedidosValidator_8java.html',1,'']]],
  ['pedidosvalidatortest_2ejava_36',['PedidosValidatorTest.java',['../PedidosValidatorTest_8java.html',1,'']]],
  ['postandputcategoryrequestdto_37',['POSTandPUTcategoryRequestDTO',['../classdev_1_1luisvives_1_1trabajoprogramacionsegundo_1_1productos_1_1dto_1_1category_1_1POSTandPUTcategoryRequestDTO.html',1,'dev::luisvives::trabajoprogramacionsegundo::productos::dto::category']]],
  ['postandputcategoryrequestdto_2ejava_38',['POSTandPUTcategoryRequestDTO.java',['../POSTandPUTcategoryRequestDTO_8java.html',1,'']]],
  ['postandputpedidorequestdto_39',['PostAndPutPedidoRequestDto',['../classdev_1_1luisvives_1_1trabajoprogramacionsegundo_1_1pedidos_1_1dto_1_1request_1_1PostAndPutPedidoRequestDto.html',1,'dev::luisvives::trabajoprogramacionsegundo::pedidos::dto::request']]],
  ['postandputpedidorequestdto_2ejava_40',['PostAndPutPedidoRequestDto.java',['../PostAndPutPedidoRequestDto_8java.html',1,'']]],
  ['postandputproductorequestdto_41',['POSTandPUTProductoRequestDTO',['../classdev_1_1luisvives_1_1trabajoprogramacionsegundo_1_1productos_1_1dto_1_1producto_1_1POSTandPUTProductoRequestDTO.html',1,'dev::luisvives::trabajoprogramacionsegundo::productos::dto::producto']]],
  ['postandputproductorequestdto_2ejava_42',['POSTandPUTProductoRequestDTO.java',['../POSTandPUTProductoRequestDTO_8java.html',1,'']]],
  ['postputdtobyuserdtotousuario_43',['postPutDtoByUserDtoToUsuario',['../classdev_1_1luisvives_1_1trabajoprogramacionsegundo_1_1usuarios_1_1mapper_1_1UsuariosMapper.html#ab61040a66aecd63f9d4abf5937005f40',1,'dev::luisvives::trabajoprogramacionsegundo::usuarios::mapper::UsuariosMapper']]],
  ['postputdtotomodel_44',['postputdtotomodel',['../classdev_1_1luisvives_1_1trabajoprogramacionsegundo_1_1productos_1_1mapper_1_1CategoriesMapper.html#a1135d3ea6c969b36001a01bbaa31f50b',1,'dev.luisvives.trabajoprogramacionsegundo.productos.mapper.CategoriesMapper.postPutDTOToModel()'],['../classdev_1_1luisvives_1_1trabajoprogramacionsegundo_1_1productos_1_1mapper_1_1ProductoMapper.html#a36cf345a6f85c1e249c578676a0544b3',1,'dev.luisvives.trabajoprogramacionsegundo.productos.mapper.ProductoMapper.postPutDTOToModel()']]],
  ['postputdtotousuario_45',['postPutDtoToUsuario',['../classdev_1_1luisvives_1_1trabajoprogramacionsegundo_1_1usuarios_1_1mapper_1_1UsuariosMapper.html#a8e202e61c6e4f476493aeeea11f09ca7',1,'dev::luisvives::trabajoprogramacionsegundo::usuarios::mapper::UsuariosMapper']]],
  ['previos_46',['Requisitos Previos',['../index.html#autotoc_md13',1,'']]],
  ['principales_3a_47',['Características principales:',['../index.html#autotoc_md51',1,'']]],
  ['proceso_20paso_20a_20paso_3a_48',['Proceso paso a paso:',['../index.html#autotoc_md55',1,'']]],
  ['producto_49',['Producto',['../classdev_1_1luisvives_1_1trabajoprogramacionsegundo_1_1productos_1_1model_1_1Producto.html',1,'dev::luisvives::trabajoprogramacionsegundo::productos::model']]],
  ['producto_2ejava_50',['Producto.java',['../Producto_8java.html',1,'']]],
  ['productoexception_51',['productoexception',['../classdev_1_1luisvives_1_1trabajoprogramacionsegundo_1_1productos_1_1exceptions_1_1ProductoException.html#ab1ba71808e939792c20493dac99a2761',1,'dev.luisvives.trabajoprogramacionsegundo.productos.exceptions.ProductoException.ProductoException()'],['../classdev_1_1luisvives_1_1trabajoprogramacionsegundo_1_1productos_1_1exceptions_1_1ProductoException.html',1,'dev.luisvives.trabajoprogramacionsegundo.productos.exceptions.ProductoException']]],
  ['productoexception_2ejava_52',['ProductoException.java',['../ProductoException_8java.html',1,'']]],
  ['productomapper_53',['ProductoMapper',['../classdev_1_1luisvives_1_1trabajoprogramacionsegundo_1_1productos_1_1mapper_1_1ProductoMapper.html',1,'dev::luisvives::trabajoprogramacionsegundo::productos::mapper']]],
  ['productomapper_2ejava_54',['ProductoMapper.java',['../ProductoMapper_8java.html',1,'']]],
  ['productomappertest_2ejava_55',['ProductoMapperTest.java',['../ProductoMapperTest_8java.html',1,'']]],
  ['productonotificaciondto_56',['ProductoNotificacionDto',['../classdev_1_1luisvives_1_1trabajoprogramacionsegundo_1_1notificaciones_1_1dto_1_1productos_1_1ProductoNotificacionDto.html',1,'dev::luisvives::trabajoprogramacionsegundo::notificaciones::dto::productos']]],
  ['productonotificaciondto_2ejava_57',['ProductoNotificacionDto.java',['../ProductoNotificacionDto_8java.html',1,'']]],
  ['productorestcontroller_58',['productorestcontroller',['../classdev_1_1luisvives_1_1trabajoprogramacionsegundo_1_1productos_1_1controller_1_1ProductoRestController.html#ad157035cf86bb70b75c4f34f4d2eace9',1,'dev.luisvives.trabajoprogramacionsegundo.productos.controller.ProductoRestController.ProductoRestController()'],['../classdev_1_1luisvives_1_1trabajoprogramacionsegundo_1_1productos_1_1controller_1_1ProductoRestController.html',1,'dev.luisvives.trabajoprogramacionsegundo.productos.controller.ProductoRestController']]],
  ['productorestcontroller_2ejava_59',['ProductoRestController.java',['../ProductoRestController_8java.html',1,'']]],
  ['productorestcontrollertest_2ejava_60',['ProductoRestControllerTest.java',['../ProductoRestControllerTest_8java.html',1,'']]],
  ['productos_61',['productos',['../index.html#autotoc_md6',1,'Gestión de Productos'],['../index.html#autotoc_md43',1,'Productos']]],
  ['productoservice_62',['ProductoService',['../interfacedev_1_1luisvives_1_1trabajoprogramacionsegundo_1_1productos_1_1service_1_1ProductoService.html',1,'dev::luisvives::trabajoprogramacionsegundo::productos::service']]],
  ['productoservice_2ejava_63',['ProductoService.java',['../ProductoService_8java.html',1,'']]],
  ['productoserviceimpl_64',['productoserviceimpl',['../classdev_1_1luisvives_1_1trabajoprogramacionsegundo_1_1productos_1_1service_1_1ProductoServiceImpl.html#a9dbcfdb22f7e2eb3d730092a620072e6',1,'dev.luisvives.trabajoprogramacionsegundo.productos.service.ProductoServiceImpl.ProductoServiceImpl()'],['../classdev_1_1luisvives_1_1trabajoprogramacionsegundo_1_1productos_1_1service_1_1ProductoServiceImpl.html',1,'dev.luisvives.trabajoprogramacionsegundo.productos.service.ProductoServiceImpl']]],
  ['productoserviceimpl_2ejava_65',['ProductoServiceImpl.java',['../ProductoServiceImpl_8java.html',1,'']]],
  ['productoserviceimpltest_2ejava_66',['ProductoServiceImplTest.java',['../ProductoServiceImplTest_8java.html',1,'']]],
  ['productsrepository_67',['ProductsRepository',['../interfacedev_1_1luisvives_1_1trabajoprogramacionsegundo_1_1productos_1_1repository_1_1ProductsRepository.html',1,'dev::luisvives::trabajoprogramacionsegundo::productos::repository']]],
  ['productsrepository_2ejava_68',['ProductsRepository.java',['../ProductsRepository_8java.html',1,'']]],
  ['productsrepositorytest_2ejava_69',['ProductsRepositoryTest.java',['../ProductsRepositoryTest_8java.html',1,'']]],
  ['proyecto_70',['proyecto',['../index.html#autotoc_md18',1,'Compilar el proyecto'],['../index.html#autotoc_md63',1,'Estadísticas del Proyecto']]],
  ['proyecto_20dale_20una_20estrella_20en_20github_71',['Si te gusta este proyecto, dale una estrella en GitHub',['../index.html#autotoc_md65',1,'']]],
  ['puedes_3a_72',['Puedes:',['../md__2home_2runner_2work_2TrabajoProgramacionSegundo_2TrabajoProgramacionSegundo_2LICENSE.html#autotoc_md69',1,'']]]
];
