var searchData=
[
  ['handlebadpriceexceptions_0',['handlebadpriceexceptions',['../classdev_1_1luisvives_1_1trabajoprogramacionsegundo_1_1common_1_1handler_1_1GlobalExceptionHandler.html#abeafcfb9f15b1df778fab839275b6ad7',1,'dev.luisvives.trabajoprogramacionsegundo.common.handler.GlobalExceptionHandler.handleBadPriceExceptions(PedidoException.BadPriceException ex)'],['../classdev_1_1luisvives_1_1trabajoprogramacionsegundo_1_1common_1_1handler_1_1GlobalExceptionHandler.html#ab39048f9d98f17f69b71a7aa952ba9fa',1,'dev.luisvives.trabajoprogramacionsegundo.common.handler.GlobalExceptionHandler.handleBadPriceExceptions(ProductoException.ValidationException ex)'],['../classdev_1_1luisvives_1_1trabajoprogramacionsegundo_1_1common_1_1handler_1_1GlobalExceptionHandler.html#a998820617464b53695a806e6a8a6e2a8',1,'dev.luisvives.trabajoprogramacionsegundo.common.handler.GlobalExceptionHandler.handleBadPriceExceptions(CategoryValidationException ex)']]],
  ['handlecategorynotfoundexceptions_1',['handleCategoryNotFoundExceptions',['../classdev_1_1luisvives_1_1trabajoprogramacionsegundo_1_1common_1_1handler_1_1GlobalExceptionHandler.html#aeb5172b71b7d1424f5978e969ecfe478',1,'dev::luisvives::trabajoprogramacionsegundo::common::handler::GlobalExceptionHandler']]],
  ['handleconstraintviolationexceptions_2',['handleConstraintViolationExceptions',['../classdev_1_1luisvives_1_1trabajoprogramacionsegundo_1_1common_1_1handler_1_1GlobalExceptionHandler.html#a80bafb8d79e0f0503a801cf2b08b218f',1,'dev::luisvives::trabajoprogramacionsegundo::common::handler::GlobalExceptionHandler']]],
  ['handledataintegrityviolationexceptions_3',['handleDataIntegrityViolationExceptions',['../classdev_1_1luisvives_1_1trabajoprogramacionsegundo_1_1common_1_1handler_1_1GlobalExceptionHandler.html#af44810566abb6c93e19a143fc280c973',1,'dev::luisvives::trabajoprogramacionsegundo::common::handler::GlobalExceptionHandler']]],
  ['handleforbiddenexceptions_4',['handleForbiddenExceptions',['../classdev_1_1luisvives_1_1trabajoprogramacionsegundo_1_1common_1_1handler_1_1GlobalExceptionHandler.html#a13b1a4fe96fc28e912225eb10ec68929',1,'dev::luisvives::trabajoprogramacionsegundo::common::handler::GlobalExceptionHandler']]],
  ['handlenolinesexceptions_5',['handleNoLinesExceptions',['../classdev_1_1luisvives_1_1trabajoprogramacionsegundo_1_1common_1_1handler_1_1GlobalExceptionHandler.html#a637bc64000536f5b09cd8ec7c729aa8d',1,'dev::luisvives::trabajoprogramacionsegundo::common::handler::GlobalExceptionHandler']]],
  ['handlenotfoundexceptions_6',['handlenotfoundexceptions',['../classdev_1_1luisvives_1_1trabajoprogramacionsegundo_1_1common_1_1handler_1_1GlobalExceptionHandler.html#a490655f28533731bfbdee0522e04c678',1,'dev.luisvives.trabajoprogramacionsegundo.common.handler.GlobalExceptionHandler.handleNotFoundExceptions(PedidoException.NotFoundException ex)'],['../classdev_1_1luisvives_1_1trabajoprogramacionsegundo_1_1common_1_1handler_1_1GlobalExceptionHandler.html#ae017ee383cf395dd4dfef3609d7c3eda',1,'dev.luisvives.trabajoprogramacionsegundo.common.handler.GlobalExceptionHandler.handleNotFoundExceptions(ProductoException.NotFoundException ex)']]],
  ['handletransporterror_7',['handleTransportError',['../classdev_1_1luisvives_1_1trabajoprogramacionsegundo_1_1notificaciones_1_1config_1_1WebSocketHandler.html#a3191e724d0cd9f46a3ccebae2c37b3fb',1,'dev::luisvives::trabajoprogramacionsegundo::notificaciones::config::WebSocketHandler']]],
  ['handlevalidationexceptions_8',['handlevalidationexceptions',['../classdev_1_1luisvives_1_1trabajoprogramacionsegundo_1_1common_1_1handler_1_1GlobalExceptionHandler.html#ac7b1064b72a0fd549f6e0f0cedc2e1e1',1,'dev.luisvives.trabajoprogramacionsegundo.common.handler.GlobalExceptionHandler.handleValidationExceptions(MethodArgumentNotValidException ex)'],['../classdev_1_1luisvives_1_1trabajoprogramacionsegundo_1_1common_1_1handler_1_1GlobalExceptionHandler.html#abcef405db3f1c46d6bd738901fab492c',1,'dev.luisvives.trabajoprogramacionsegundo.common.handler.GlobalExceptionHandler.handleValidationExceptions(PedidoException.ValidationException ex)']]]
];
